### ISSUE TITLE
Generating embeddings problem

### ISSUE THREAD

**Issue by buaanlsdewm** [danhper/bigcode-tools#10]
@tuvistavie hello,i use your bigcode-tools to generate token embeddings.i get problems when running the code ‘docker-bigcode bigcode-ast-tools generate-vocabulary --strip-identifiers -o workspace/java-vocabulary-no-ids.tsv workspace/apache-commons-asts.json’ in step 4 in the tutorial，you can see the bug in the following image.Can you solve the problem?thank you
![1](https://user-images.githubusercontent.com/38215243/66464390-78e69880-eab1-11e9-8808-567854829a87.PNG)

**Comment by danhper** [comment]
This should be fixed by https://github.com/danhper/bigcode-tools/commit/ce54697bff0f77bca1c5f24ea72a8d3bd5f1def6, please let me know if you still run into any issue.
