### ISSUE TITLE
About bigcode-ast-tool skip-gram generation with ancestors

### ISSUE THREAD

**Issue by Eduardo95** [danhper/bigcode-tools#15]
Hello,

Great work on this tool. I have a question when I am trying to use this tool. 

I followed the tutorial that you provided on the github page. When I try to generate skipgram-like data, the (input, output) pairs all appear twice. You can see the results in the picture.

<img width="632" alt="Screen Shot 2020-06-28 at 8 55 21 PM" src="https://user-images.githubusercontent.com/13105907/85948138-b2ce3680-b981-11ea-8e0f-a79d8edd5cdc.png">

To be clear, I followed the exact same instructions that you provided in the tutorial. Can you tell me why this happened?

Thank you

**Comment by Eduardo95** [comment]
I think the logic for the parameter '--ancestors-window-size' might have some problems. Because when I set this parameter to 1, the output seems to be normal.

**Comment by Eduardo95** [comment]
<img width="562" alt="Screen Shot 2020-06-28 at 9 19 45 PM" src="https://user-images.githubusercontent.com/13105907/85948760-23c31d80-b985-11ea-85e5-ef00bbb20371.png">

You can see from the picture. With the same ast file and the same vocabulary file, when I set the parameter of '--ancestors-window-size' to 1, 2, 3, the generated file size is 1451, 2902, 4353, respectively.

In my understanding, the function of this parameter is to control the window size of contexts. It seems your implementation simply repeats the process of the same ancestor instead of different ancestors.

**Comment by danhper** [comment]
Thanks for the detailed report, this was indeed a very stupid bug.
This should be fixed with https://github.com/danhper/bigcode-tools/commit/94ce416fbb40b9b25d49bf88284bf7ccb6132bd3#diff-1b41bff399bdb82ab06ade6be5dc0459R79
